#!/system/bin/sh
adb connect 192.168.1.101 && adb -s 192.168.1.101:5555 shell dumpsys battery | grep 'AC powered: true' && monkey -p com.oneyue.tv -c android.intent.category.LAUNCHER 1 || am force-stop com.oneyue.tv
