#!/bin/zsh
for page in `seq 1 48`;do
curl 'https://list.jd.com/list.html?cat=670,686,690&ev=exprice%5FM0L100%402379%5F58350&page='$page | grep addcart | grep -Po 'pid=\K(\d+)' | xargs -P 10 -n1 ./size | tee -a mouse-size-list
done
